name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    
    # 1️⃣ Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Run Gitleaks
    - name: Run Gitleaks scan
      uses: gitleaks/gitleaks-action@v2
      with:
        args: detect --source . --verbose

    # 3️⃣ Docker Login
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4️⃣ Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t cloudketan/nodejs-hpa-vpa:hv1 .

    # 5️⃣ Push Docker Image
    - name: Push Docker image
      run: |
        docker push cloudketan/nodejs-hpa-vpa:hv1

    # 6️⃣ Apply ArgoCD Application
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f argocd/application.yaml
