name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    # 1️⃣ Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Run Gitleaks
    - name: Run Gitleaks scan
      uses: gitleaks/gitleaks-action@v2
      with:
        args: detect --source . --verbose

    # 3️⃣ Setup Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4️⃣ Docker Login
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5️⃣ Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: cloudketan/nodejs-hpa-vpa:hv1

    # 6️⃣ Setup kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    # 7️⃣ Apply ArgoCD Application
    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f argocd/application.yaml
